font_family DejaVuSansM Nerd Font Mono
font_size 16.0
# modify_font cell_height 90%
# modify_font baseline 3
cursor_trail 1
cursor_beam_thickness 0
window_padding_width 5
background_opacity 0.8
background_blur 32
macos_option_as_alt yes


# BEGIN_KITTY_THEME
# Jellybeans
include current-theme.conf
# END_KITTY_THEME
