# true color support
set -g default-terminal "screen-256color"

# set escape-time
set -sg escape-time 0

# enable mouse
set -g mouse on

# prefix-r to source ~/.tmux.conf
unbind r
bind r source-file ~/.tmux.conf

# set prefix to C-s
set -g prefix C-s
unbind C-b
bind-key C-s send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# don't rename windows automatically
set-option -g allow-rename off
