### SETTINGS ###

set -g default-terminal "tmux-256color"
set -g focus-events on
set -sg escape-time 0
set -g mouse on
set -s extended-keys on
set -g extended-keys-format csi-u

set -g status-position top
set -g status-style "bg=default"
set -g status-right ""

# vi mode
setw -g mode-keys vi

# start windows and panes at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set -g renumber-windows on
set -g detach-on-destroy off

# renumber sessions
set-hook -g session-created "run $XDG_CONFIG_HOME/tmux/renumber-sessions.sh"
set-hook -g session-closed  "run $XDG_CONFIG_HOME/tmux/renumber-sessions.sh"

### PLUGINS ###

set -g @plugin "tmux-plugins/tpm"
set -g @plugin "christoomey/vim-tmux-navigator"

### KEYBINDINGS ###

# reload
unbind r
bind r source-file "$XDG_CONFIG_HOME/tmux/tmux.conf"

# splits
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# navigation
bind-key -n "M-h" previous-window
bind-key -n "M-l" next-window
bind c new-window -c "#{pane_current_path}"

# navigation
bind-key -n "M-h" previous-window
bind-key -n "M-l" next-window
bind c new-window -c "#{pane_current_path}"

# Smart pane navigation with vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(g?vim?x?|nvim)$'"

bind-key -n "C-h" if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind-key -n "C-j" if-shell "$is_vim" "send-keys C-j" "select-pane -D"
bind-key -n "C-k" if-shell "$is_vim" "send-keys C-k" "select-pane -U"
bind-key -n "C-l" if-shell "$is_vim" "send-keys C-l" "select-pane -R"

# bind prefix+s to open a fuzzy session switcher in a popup
bind s display-popup -w 80% -h 80% -E "tmux list-sessions -F '#{session_name}' | fzf --reverse --preview 'tmux capture-pane -p -e -t {}' | xargs tmux switch-client -t"

bind g display-popup -E -w 80% -h 80% -d "#{pane_current_path}" lazygit
bind G run-shell "$XDG_CONFIG_HOME/tmux/open-github.sh"

### TPM INITIALIZE (must be at the very bottom) ###
run "$XDG_CONFIG_HOME/tmux/plugins/tpm/tpm"
